### PR TITLE
Connect-frontend-frameworks

### PR DESCRIPTION
**Pull request by olaishola05**
# "Hello world" project with two apps
- Backend
   - Create a new Rails API app called 'hello-rails-back-end' with Postgres database.
   - Initialize your project with Git.
   - Create a table for storing your messages and create 5 different greetings.
   - Create an API endpoint that selects a random greeting from your table
   - Create a new React app called 'hello-react-front-end'
- Front End
   - Initialize your project with Git.
   - Create an App component with react-router.
   - Create the Greeting component that displays a greeting & set it up as a route in the App component.
   - Create a store, an action, and a reducer that connects the API endpoint to get the random greeting.
   - Display the random greeting in your Greeting component.
PR link for the backend: [PR](https://github.com/netman5/hello-rails-back-end/pull/3)

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
### Hi @netman5 :slightly_smiling_face: 

Good job so far!
However, there is an issue you need to work on, to go to the next project; but you are almost there!


## Required Changes ♻️

- [ ] In your backend code, you wrapped your model class through several folders.  Considering the way you structured your file, I had to modify the code in your seeds.rb file, like so, in order to seed the database.

``` 
Api::V1::Greeting.create(:messagee => "Bonjour")
```
Kindly modify the file access, in seeds.rb, like I did, or if you want to leave them as it is; remove the greeting class from the folders, then make the necessary adjustments to the greetings controller so the api works fine.

- [ ] You need to open a PR for the rails [api backend](https://github.com/netman5/hello-rails-back-end/pulls)

## [**Optional**] 
In your frontend code, separate actions and reducers in different files.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by olaishola05** [comment]
Thank you @uche-inyama we implement that asap.

**Comment by Emmyn5600** [comment]
@netman5 Please work on the changes requested by the previous reviewer. You didn't work on them as requested because nothing is working when you click on the button.

image

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
Hi @netman5 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- Check the comment under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahmetbozaci** [comment]
# STATUS: INVALID  ❌ 


### Hello @netman5  ✋🏼 
#### You have submitted a project, the rails part has not to pull request. Please check the [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/hello_world_two_apps.md#:~:text=In%20the%20README,PR%20with%20changes.) and send a review again.
#### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


### Cheers and Happy coding! 💻 👏
coding


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

_Invalid Code Review Request **does not count** into the code reviews limit._

___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Review by descholar-ceo — APPROVED** [review]
Hi @netman5 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
